name: Unit-Testing
on:
  push:
    branches:
      - "*"

jobs:
  linting:
    name: Unit-Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.5
      - name: Install dependencies
        run: npm ci
      - name: Unit-Testing
        run: npm run lint
